src/WebApi/appsettings.Development.json
src/WebApi/appsettings.json

Add option of both local DB and docker DB

 ✨Ensure Smoother F5 Experience

---

.github/dependabot.yml
.github/workflows/codeql.yml
.github/workflows/publish-log4brains.yml

Doing this as per https://github.com/dorny/test-reporter/issues/67
Otherwise the test results workflow may attach the report to the wrong workflow

Workflows - run CodeQL and ADR report publishing after main workflow

---

src/Application/Common/Behaviours/LoggingBehaviour.cs
src/Application/Common/Behaviours/PerformanceBehaviour.cs
src/Application/Common/Behaviours/UnhandledExceptionBehaviour.cs
src/Application/Common/Behaviours/ValidationBehaviour.cs
src/Application/Common/Exceptions/ValidationException.cs
src/Application/Features/TodoItems/Commands/CompleteTodoItem/CompleteTodoItemCommand.cs
src/Application/Features/TodoItems/Commands/CreateTodoItem/CreateTodoItemCommand.cs
src/Application/Features/TodoItems/EventHandlers/TodoItemCreatedEventHandler.cs
src/Application/Features/TodoItems/Queries/GetAllTodoItems/GetAllTodoItemsQuery.cs
src/Infrastructure/Persistence/ApplicationDbContext.cs
src/Infrastructure/Persistence/ApplicationDbContextInitializer.cs
src/Infrastructure/Persistence/Interceptors/DispatchDomainEventsInterceptor.cs
src/Infrastructure/Persistence/Interceptors/EntitySaveChangesInterceptor.cs
src/WebApi/HealthChecks/EntityFrameworkDbContextHealthCheck/EntityFrameworkDbContextHealthCheck.cs
src/WebApi/Services/CurrentUserService.cs

Constructors for a several classes across the project have been refactored to take advantage of shortcut syntax. The changes reduce the amount of boilerplate code and increase readability. This also brings the code in line with modern conventions.

♻️ Refactor constructors to use new primary constructors syntax

---

docs/adr/20231212-subcutaneous-tests-should-target-webapi-layer.md

The commit adds a new Architecture Decision Record (ADR) where it was decided to change the target of subcutaneous tests from the Application Layer to the WebApi Layer. This decision will make the tests more comprehensive by including other important aspects such as serialization and web authorization.

📝 Add new ADR about targeting WebApi layer for subcutaneous tests

---

SSW.CleanArchitecture.sln

This will make the WebApi project the default startup project.
To test this in Visual Studio, delete `.vs` and run Visual Studio.

♻️ Updated order of the project in sln to make WebApi startup project by default

---

src/WebApi/WebApi.csproj

This is a hacky thing to do - ideally the removal of this should be part of the templating process.

WebApi - remove usersecrets prop

---

.github/workflows/meta-test.yml

No PBIs - I just did it in my own personal repo & figured its a good idea for CA template too!
✏️  Added an integration test that runs on main/PRs that checks that the dotnet new templates work as expected.
✏️ 
No
Figure: The test creating a dotnet new template & building

🧪 Create a meta-integration test

---

README.md
SSW.CleanArchitecture.sln
src/Infrastructure/DependencyInjection.cs
src/Infrastructure/Infrastructure.csproj
src/Infrastructure/Persistence/ApplicationDbContext.cs
src/WebApi/Program.cs
tests/WebApi.IntegrationTests/Common/Fixtures/IntegrationTestWebApplicationFactory.cs
tests/WebApi.IntegrationTests/Common/Fixtures/ServiceCollectionExt.cs
tests/WebApi.IntegrationTests/Common/Fixtures/TestingDatabaseFixture.cs
tests/WebApi.IntegrationTests/WebApi.IntegrationTests.csproj
tools/Database/ApplicationDbContextInitializer.cs
tools/Database/Database.csproj
tools/Database/Program.cs
tools/Database/appsettings.json
up.ps1

✏️ #294 
✏️ Previously DB creation and data seeding was done in `Program.cs` in Development mode.  There is risk that this might be run on PROD which isn't great.P
Migrated DB migrations and seeding to a new project under `Tools\Database`.  This project is then called by `up.ps1` to handle creation of SQL Server, DB, and Seed data all in one command.
✏️ Yes with @william-liebenberg

👷‍♂️ 306  move seed data and migrations out of api

---

docker-compose.yml
src/WebApi/appsettings.Development.json
tools/Database/appsettings.json

✏️ CA workshop
✏️ Change default SQL Server port to 1500.  This is to avoid conflicts with any local install of MS SQL Server
✏️  No

Update default SQL server port to 1500

---

README.md

Following the Clean Architecture Chewing the Fat
Added an instruction stating which URL to load to view the Swagger output and thereby demonstrate that the project is working.
No

📝 README - Add browser view step

---

Directory.Build.props
global.json
src/Application/Application.csproj
src/Infrastructure/Infrastructure.csproj
src/WebApi/WebApi.csproj
tests/Directory.Packages.props
tools/Database/Database.csproj

✏️ https://github.com/SSWConsulting/SSW.CleanArchitecture/issues/374
✏️ Updated to .NET 9 RC 2
✏️ No

📦 374  upgrade template to net 9 rc 2

---

.github/workflows/codeql.yml

#388 
Github runners currently do not have the .NET 9 RC2 SDK installed. Need to install manually with action.
no

🐛 CodeQL - Fix Build

---

tools/AppHost/AppHost.csproj
tools/AppHost/Commands/SqlServerCommandExt.cs
tools/AppHost/Program.cs
tools/MigrationService/Initializers/DbContextInitializerBase.cs

✏️ https://github.com/SSWConsulting/SSW.CleanArchitecture/issues/410
✏️ Added command to drop database on demand. This is useful when not using migrations and the DB schema needs to be recreated. With this command we can now drop the db and re-run the migration service without making changes to our code.
✏️ No

✨ Added command to drop database on demand

---

src/Application/UseCases/Teams/Queries/GetTeam/GetTeamQuery.cs

✏️ https://github.com/SSWConsulting/SSW.CleanArchitecture/issues/425
✏️ 
This pull request includes changes to the `GetTeamQuery` and `GetAllTeamsQueryHandler` to improve error handling in the `GetTeam` use case.
Error handling improvements:
* [`src/Application/UseCases/Teams/Queries/GetTeam/GetTeamQuery.cs`](diffhunk://#diff-3fbc5e7658ae01783b013a3e11f46cbfaac9ead368136a94c47d09fc19b5195fL6-R10): Updated the `GetTeamQuery` to return `ErrorOr<TeamDto>` instead of `TeamDto?` to better handle errors.
* [`src/Application/UseCases/Teams/Queries/GetTeam/GetTeamQuery.cs`](diffhunk://#diff-3fbc5e7658ae01783b013a3e11f46cbfaac9ead368136a94c47d09fc19b5195fR26-R28): Modified the …

✨ Show example of using ErrorOr in a query

---

global.json
src/Application/Application.csproj
src/Infrastructure/Infrastructure.csproj
src/WebApi/WebApi.csproj
tests/Directory.Packages.props
tools/AppHost/AppHost.csproj
tools/MigrationService/MigrationService.csproj
tools/MigrationService/Worker.cs

#433 
This pull request includes several updates to package versions across multiple project files, transitioning from release candidates and preview versions to stable versions.
* [`global.json`](diffhunk://#diff-8df3cd354bc584349d04ad5675b33c042d8b99b741b8b95af394c55e0f5001bfL3-R5): Updated .NET SDK version to `9.0.100` and set `allowPrerelease` to `false`.
* [`src/Application/Application.csproj`](diffhunk://#diff-21ffebced6af4a53e697d1f5abf63e74d55d0d5828c1b530c6721285540a8e70L15-R17): Updated `Microsoft.EntityFrameworkCore`, `Microsoft.Extensions.DependencyInjection.Abstractions`, and `Microsoft.Extensions.Logging.Abstractions` to version `9.0.0`.
* …

📦 433 net 9 upgrade

---

docs/adr/20241118-produce-useful-sql-server-exceptions.md
docs/adr/20241118-replace-automapper-with-manual-mapping.md
docs/adr/20241118-use-vogen-to-simplify-strongly-typed-ids.md
src/Application/UseCases/Heroes/Commands/UpdateHero/UpdateHeroCommand.cs
src/Application/UseCases/Teams/Commands/AddHeroToTeam/AddHeroToTeamCommand.cs
src/Application/UseCases/Teams/Commands/CompleteMission/CompleteMissionCommand.cs
src/Application/UseCases/Teams/Commands/ExecuteMission/ExecuteMissionCommand.cs
src/Application/UseCases/Teams/Events/PowerLevelUpdatedEventHandler.cs
src/Application/UseCases/Teams/Queries/GetTeam/GetTeamQuery.cs
src/Domain/Domain.csproj
src/Domain/Heroes/Hero.cs
src/Domain/Heroes/Power.cs
src/Domain/Teams/Mission.cs
src/Domain/Teams/Team.cs
src/Infrastructure/Persistence/ApplicationDbContext.cs
src/Infrastructure/Persistence/Configuration/HeroConfiguration.cs
src/Infrastructure/Persistence/Configuration/MissionConfiguration.cs
src/Infrastructure/Persistence/Configuration/TeamConfiguration.cs
src/Infrastructure/Persistence/Configuration/VogenEfCoreConverters.cs
tests/Architecture.Tests/DomainTests.cs
tests/Domain.UnitTests/Heroes/HeroTests.cs
tests/Domain.UnitTests/Teams/MissionTests.cs
tests/Domain.UnitTests/Teams/TeamTests.cs
tests/WebApi.IntegrationTests/Endpoints/Heroes/Commands/UpdateHeroCommandTests.cs

https://github.com/SSWConsulting/SSW.CleanArchitecture/issues/364
This pull request includes several changes aimed at refactoring the codebase to use strongly typed IDs and improving the configuration of the Entity Framework Core (EF Core) models. The most important changes include the introduction of the `Vogen` library for value objects, updates to the `HeroId`, `TeamId`, and `MissionId` types, and adjustments to the entity configurations.
Refactoring to use strongly typed IDs:
* [`src/Domain/Heroes/Hero.cs`](diffhunk://#diff-094ca6729cc59148d9d65db00c747f8731a9f56aed4f12867002e9a94daa978eL1-R8): Replaced the `HeroId` struct with a `Vogen` value object and updated the `Create` …

✨ 364 Add Vogen for Strongly Typed IDs

---

docs/adr/20241118-produce-useful-sql-server-exceptions.md
docs/adr/20241118-replace-automapper-with-manual-mapping.md
docs/adr/20241118-use-vogen-to-simplify-strongly-typed-ids.md
src/WebApi/Extensions/CustomProblemDetailsExt.cs
src/WebApi/Extensions/CustomScalarExt.cs
src/WebApi/Program.cs

https://github.com/SSWConsulting/SSW.CleanArchitecture/issues/431
This pull request includes several changes to improve the handling of exceptions and API references in the `WebApi` project, as well as updates to ADR documentation statuses. The most important changes are grouped by theme below:
* Updated the status of ADR documents from "approved" to "accepted" to reflect the current decision status. (`docs/adr/20241118-produce-useful-sql-server-exceptions.md`, `docs/adr/20241118-replace-automapper-with-manual-mapping.md`, `docs/adr/20241118-use-vogen-to-simplify-strongly-typed-ids.md`) [[1]](diffhunk://#diff-60ebb93559b2ee4bc3c13eb0b97698d2fe4869c82456e52936ebad070a89f02fL3-R3) …

✨ 431 enhanced problem details

---

src/Domain/Common/Base/AggregateRoot.cs
src/Domain/Common/Base/Auditable.cs
src/Domain/Common/EventualConsistency/EventualConsistencyError.cs
src/Domain/Common/EventualConsistency/EventualConsistencyException.cs
src/Domain/GlobalUsings.cs
src/Domain/Heroes/Hero.cs
src/Domain/Heroes/HeroErrors.cs
src/Domain/Heroes/PowerLevelUpdatedEvent.cs
src/Domain/Heroes/TeamByIdSpec.cs
src/Domain/Teams/Mission.cs
src/Domain/Teams/MissionErrors.cs
src/Domain/Teams/Team.cs
src/Domain/Teams/TeamByIdSpec.cs
src/Domain/Teams/TeamErrors.cs
src/Infrastructure/Middleware/EventualConsistencyMiddleware.cs
tools/MigrationService/Worker.cs

https://github.com/SSWConsulting/SSW.CleanArchitecture/issues/338
This pull request involves several changes aimed at cleaning up unused `using` directives and adding global using directives to the `GlobalUsings.cs` file. Below is a summary of the most important changes:
* [`src/Domain/Common/Base/AggregateRoot.cs`](diffhunk://#diff-6673bbfbcc38dcf827ffdbccca815084ddf5f14b41095c98e332260288e16ca2L1-R1): Removed unused `using` directives (`SSW.CleanArchitecture.Domain.Common.Interfaces` and `System.ComponentModel.DataAnnotations.Schema`).
* [`src/Domain/Common/Base/Auditable.cs`](diffhunk://#diff-7f61c1a655bdfa4cd99a37fba4dcc331ab6a49393378babd32b03927376e375cL1-R1): Removed …

💬 Added links to specification rule

---

README.md

This pull request includes a small change to the `README.md` file. The change updates the link to the contributing guidelines to use a relative path for better accessibility.
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L223-R223): Updated the link to the contributing guidelines from `contributing.md` to `./CONTRIBUTING.md`.

📝 Fix Contributing Link

---

src/Application/Common/Interfaces/ICurrentUserService.cs
src/Domain/Common/Interfaces/IAggregateRoot.cs
src/Domain/Common/Interfaces/IAuditable.cs

> 1. What triggered this change? (PBI link, Email Subject, conversation + reason, etc)
✏️ I noticed warnings from unneeded modifiers
✏️ Remove public modifiers from public interfaces
✏️ No

Removed unneeded interface modifiers

---

src/Application/Application.csproj
src/Infrastructure/Infrastructure.csproj
src/WebApi/WebApi.csproj
tests/Directory.Packages.props
tools/AppHost/AppHost.csproj
tools/MigrationService/MigrationService.csproj

Release of Aspire 9.1
This pull request includes updates to various package references across multiple project files to ensure compatibility and take advantage of the latest features and bug fixes. The changes primarily involve upgrading the versions of several dependencies.
Dependency updates:
* [`src/Application/Application.csproj`](diffhunk://#diff-21ffebced6af4a53e697d1f5abf63e74d55d0d5828c1b530c6721285540a8e70L16-R18): Updated `Microsoft.EntityFrameworkCore`, `Microsoft.Extensions.DependencyInjection.Abstractions`, and `Microsoft.Extensions.Logging.Abstractions` from version 9.0.0 to 9.0.2.
* [`src/Infrastructure/Infrastructure.csproj`](diffhunk://#diff-57ba390570d83de5303d52 …

Upgrade aspire to 9.1 and microsoft extensions to latest

---

Directory.Build.props

Using the latest and greatest code analyzers is excellent, however there are a couple of code warnings that, in my opinion, we should be more lenient with:
**Figure: Single command `else` statements are fairly common.**
**Figure: developers will often want to add whitespace for readability**
- Add explicit `NoWarn` for these 2 warnings in `Directory.Build.Props`:
```
<NoWarn>$(NoWarn);IDE0055</NoWarn>
<NoWarn>$(NoWarn);IDE0011</NoWarn>
```
✏️

:recycle: add NoWarn for common code style use cases

---

.github/workflows/publish-log4brains.yml

This pull request includes updates to the GitHub Actions workflow for publishing Log4brains. The changes primarily focus on adding manual triggering capabilities and updating the deployment action version.
Improvements to workflow configuration:
* [`.github/workflows/publish-log4brains.yml`](diffhunk://#diff-4ac665e28c3b53aecd510cf3e9cb851e01c4a42b0e34546d8c6afdcc1599cf5aR6): Added `workflow_dispatch` to allow manual triggering of the workflow.
Updates to deployment action:
* [`.github/workflows/publish-log4brains.yml`](diffhunk://#diff-4ac665e28c3b53aecd510cf3e9cb851e01c4a42b0e34546d8c6afdcc1599cf5aL28-R34): Updated `JamesIves/github-pages-deploy-action` from version `v4.6.9` to `v4.7.3` and adjusted the input parameters to match the new version's requirements.

👷 Fix log4brains publish

---

.github/workflows/publish-log4brains.yml

This pull request includes updates to the `.github/workflows/publish-log4brains.yml` file to ensure compatibility with the latest Node.js version and to simplify the build process for Log4brains.
Key changes:
* Updated the Node.js version from `14` to `21` in the `Install Node` step to use the latest version.
* Simplified the Log4brains build command by removing the `--basePath` option.
* Removed the `branch` parameter from the `Deploy` step, which is no longer necessary.

👷 Fix log4brains v2

---

.github/workflows/publish-log4brains.yml
Directory.Packages.props
docs/adr/20250326-migrate-to-awesome-assertions.md
tests/Architecture.Tests/Architecture.Tests.csproj
tests/Architecture.Tests/Common/TestResultAssertions.cs
tests/Architecture.Tests/Common/TestResultExtensions.cs
tests/Domain.UnitTests/Domain.UnitTests.csproj
tests/WebApi.IntegrationTests/WebApi.IntegrationTests.csproj

This pull request includes changes to migrate from FluentAssertions to Awesome Assertions, update the build process, and modify test projects accordingly. The most important changes include updating the build command, modifying package references, and adjusting test assertion implementations.
See [ADR](https://github.com/SSWConsulting/SSW.CleanArchitecture/pull/497/files#diff-da7198a0bdb512642da58ed90a385d9176f044bd583dee858ca76cbf9d08a4d4)
Figure: Majority of the SAW team are in favor of this change
Migration to Awesome Assertions:
* [`Directory.Packages.props`](diffhunk://#diff-5baf5f9e448ad54ab25a091adee0da05d4d228481c9200518fcb1b53a65d4156R15): Added `AwesomeAssertions` package and removed `FluentAssertions` package. [[1]](diffhunk://#diff-5baf5f9e448ad54ab25a091adee0da05d4d228481c9200 …

🧪 Migrate to Awesome Assertions

---

Directory.Packages.props
src/Application/Common/Behaviours/PerformanceBehaviour.cs
src/Application/Common/Behaviours/UnhandledExceptionBehaviour.cs
src/Application/Common/Behaviours/ValidationErrorOrResultBehaviour.cs
tests/WebApi.IntegrationTests/WebApi.IntegrationTests.csproj

This pull request includes updates to package versions and improvements to the handling of cancellation tokens in several behaviors. The most important changes are listed below:
* Updated `AwesomeAssertions` to version 8.1.0 and `Bogus` to version 35.6.2 in `Directory.Packages.props`.
* Updated `MediatR` to version 12.5.0 and various `Microsoft` packages to new versions in `Directory.Packages.props`.
* Updated `OpenTelemetry` packages to the latest versions in `Directory.Packages.props`.
* Updated `Scalar.AspNetCore`, `Testcontainers`, `Testcontainers.MsSql`, `Vogen`, and `xunit.v3` to new versions in `Directory.Packages.props`.
* Added `cancellationToken` to the `next` method calls in `PerformanceBehaviour`, `UnhandledExceptionBehaviour`, and `ValidationErrorOrResultBehaviour` to improve …

⬆️ Update Nuget Packages

---

CleanArchitecture.nuspec

This pull request includes updates to the `CleanArchitecture.nuspec` file, focusing on versioning and cleanup.
Version update:
* Updated the version number from `2025.03.03` to `2025.04.07` to reflect the latest release.
File cleanup:
* Removed an unnecessary comment (``) from the `CleanArchitecture.nuspec` file to maintain a clean and professional codebase.

🚀 Update version to 2025.04.07

---

Directory.Packages.props
tools/AppHost/AppHost.csproj
tools/AppHost/Commands/SqlServerCommandExt.cs

This pull request updates several package versions and simplifies the implementation of the `WithDropDatabaseCommand` method in the `SqlServerCommandExt` class. The most important changes include upgrading dependencies in `Directory.Packages.props`, updating the SDK version in `AppHost.csproj`, and refactoring the database command logic.
* Updated the versions of `Aspire.Hosting.AppHost`, `Aspire.Hosting.SqlServer`, and `Aspire.Microsoft.EntityFrameworkCore.SqlServer` packages from `9.1.0` to `9.2.1` in `Directory.Packages.props`.
* Updated the versions of `Microsoft.Extensions.Diagnostics.HealthChecks` and `Microsoft.Extensions.DependencyInjection.Abstractions` packages from `9.0.3` to `9.0.4` in `Directory.Packages.props`.
* Updated the SDK version in `AppHost.csproj` from `9.1.0` to …

⬆️ Update Aspire.Hosting and related packages to version 9.2.0 and 9.2.1; refactor drop-database command

---

tools/MigrationService/Worker.cs

This pull request makes a minor refactor to the `Worker.cs` file in the migration service, improving code clarity by renaming a local variable for consistency.
* Refactored the local variable name from `warehouseInitializer` to `initializer` throughout the `ExecuteAsync` method in `Worker.cs` for improved clarity and consistency.

✨ Rename variable for clarity in database initialization

---

README.md

✏️ As an intern, while exploring and learning how to use the CA template utilising migrations required significant trial and error. After discussion with @lukecookssw we determined the procedure required to add and remove migrations cleanly.
✏️ A section was added to the README.md file, consistent with the styling of the rest of the file, detailing the commands and procedures required to add and remove migrations including any arguments or tools required. 
✏️ I worked with @lukecookssw.

📝Documentation for EF Core migrations

---

.aspire/settings.json
Directory.Packages.props
tools/AppHost/AppHost.cs
tools/AppHost/AppHost.csproj

This pull request primarily updates package dependencies to newer versions across the project and introduces configuration changes for improved development compatibility. The most notable change is the switch to SQL Server 2022 for local container development, addressing cross-platform issues with SQL Server 2025. Additionally, the Aspire SDK and related packages are updated, and a new settings file is added for AppHost configuration.
**Dependency updates:**
* Updated multiple package versions in `Directory.Packages.props`, including major Aspire, Ardalis, Microsoft, Polly, and other dependencies to their latest releases for improved features and compatibility. [[1]](diffhunk://#diff-5baf5f9e448ad54ab25a091adee0da05d4d228481c9200518fcb1b53a65d4156L6-R20) …

aspire-9.5-update
