.github/workflows/dotnet.yml
src/WebApi/nswag.json

👷 Add build action

---

src/Application/Features/TodoItems/Commands/CreateTodoItem/CreateTodoItemCommand.cs
src/Application/Features/TodoItems/Commands/CreateTodoItem/TodoItemCreatedEvent.cs
src/Application/Features/TodoItems/EventHandlers/TodoItemCreatedEventHandler.cs
src/Domain/Common/BaseEntity.cs
src/Domain/Common/BaseEvent.cs
src/Domain/Domain.csproj
src/Domain/Events/TodoItemCreatedEvent.cs
src/Infrastructure/Common/MediatorExtensions.cs
src/Infrastructure/Persistence/ApplicationDbContext.cs

🔙 Restore Domain events

---

LICENSE

MIT because it is permissive & allows private use

🧑‍⚖️ Create LICENSE

---

.vscode/settings.json
src/Domain/Domain.csproj
src/WebApi/WebApi.csproj
src/WebApi/appsettings.json

- Remove secret ID from project file to avoid same secrets file being used for different usages of the template.
- Added more realistic sample connection string
- Added setting to help VSCode open the solution
- Tidied up project files

🐛 67 remove static user secrets

---

LICENSE

As per my conversation with Cameron, we should use this name

⚖️ Use Legal Name

---

CleanArchitecture.nuspec

🚀 Updated nuget package version to 0.6.0

---

.github/workflows/codeql.yml
global.json
src/Application/Application.csproj
src/Domain/Domain.csproj
src/Infrastructure/Infrastructure.csproj
src/WebApi/WebApi.csproj
src/WebApi/nswag.json
src/WebApi/wwwroot/api/specification.json
tests/Application.IntegrationTests/Application.IntegrationTests.csproj
tests/Application.UnitTests/Application.UnitTests.csproj
tests/Application.UnitTests/Features/TodoItems/Specifications/TodoItemByTitleSpecTests.cs
tests/Architecture.Tests/Architecture.Tests.csproj
tests/Domain.UnitTests/Domain.UnitTests.csproj

Upgrade all projects to .NET 8.0rc2

---

README.md

📝 Add repobeats repo analytics

---

README.md

Extra sections like "Installing the Template", "Adding a Feature", and "Running the Solution" have been added to provide comprehensive step-by-step guidelines. This should make it easier to follow along and understand the process.

📝 Added separate sections under 'Getting Started'.

---

README.md

Also moved publishing template section towards the bottom.

📝 Added training section to readme

---

.github/workflows/publish-log4brains.yml

✏️ Broken build
✏️ Log4Brains workflow
✏️  No

🐛 Revert recent to Log4Brains workflow

---

CleanArchitecture.nuspec

fixes this bad commit https://github.com/SSWConsulting/SSW.CleanArchitecture/commit/08c35b44e84586ddfb8f19d427a8900f8c5cbefc#diff-4090f9e2541e5897e995e3ae3c6af7dcfeaf944381e83bf18d5a19f824a7823cL34-R34

Include templates in the package

---

CleanArchitecture.nuspec
README.md
package.ps1

✏️ Feburary monthly update
✏️ Switching to CalVer
✏️  No

🚀 Switch to CalVer

---

.template.config/template.json
CleanArchitecture.nuspec

✏️ Fixes #210  - unwanted files are included in the template output
✏️  Requested files and folders were added to exclusions in `template.json`
**Figure: Unwanted files and folders (see linked issue) are no longer included**
✏️ No

Remove non template files

---

.github/dependabot.yml

Added day/time/timezones for scans
PRs - added prefixes
I noticed deprecation messages in Action logs and that Dependabot hadn't picked up any updates that would've resolved them
Dependabot config
Note: I'm leaving the actions untouched (with deprecated dependencies) by design - Dependabot should update them when it next runs
> 3. Did you do pair or ~mob~ ensemble programming?
no

Make dependabot work

---

docs/adr/20240415-replace-string-length-constraints-with-better-business-rules.md
src/Domain/Common/Constants.cs
src/Domain/Heroes/Hero.cs
src/Domain/Heroes/Power.cs
src/Domain/Teams/Mission.cs
src/Infrastructure/Persistence/Configuration/HeroConfiguration.cs
src/Infrastructure/Persistence/Configuration/MissionConfiguration.cs
src/Infrastructure/Persistence/Configuration/TeamConfiguration.cs
src/Infrastructure/Persistence/Migrations/20240415050433_Remove_StringLength_Constraints.Designer.cs
src/Infrastructure/Persistence/Migrations/20240415050433_Remove_StringLength_Constraints.cs
tests/Domain.UnitTests/Heroes/HeroTests.cs
tests/Domain.UnitTests/Heroes/HeroesTests.cs
tests/Domain.UnitTests/Heroes/PowerTests.cs
tests/Domain.UnitTests/Teams/MissionTests.cs
tests/Domain.UnitTests/Teams/TeamTests.cs

✏️  #285 
- Domain.UnitTests: Added tests for `Hero`, `Power`, `Team`, and `Mission`
No.

✨ Replace string length constraint with business logic guards, and add unit tests

---

src/Application/Common/Interfaces/IApplicationDbContext.cs
src/Application/Features/Heroes/Commands/CreateHero/CreateHeroCommand.cs
src/Application/Features/Heroes/Commands/CreateHero/CreateHeroPowerDto.cs
src/Application/Features/Heroes/Commands/UpdateHero/UpdateHeroCommand.cs
src/Application/Features/Heroes/Commands/UpdateHero/UpdateHeroPowerDto.cs
src/Application/Features/Heroes/Queries/GetAllHeroes/GetAllHeroesMapping.cs
src/Application/Features/Heroes/Queries/GetAllHeroes/GetAllHeroesQuery.cs
src/Application/Features/Heroes/Queries/GetAllHeroes/HeroDto.cs
src/Domain/Heroes/Hero.cs
src/Infrastructure/Persistence/Configuration/TeamConfiguration.cs
src/Infrastructure/Persistence/Migrations/20240415072043_Remove_Hero_Team_EF_Config_RequiredFlag.Designer.cs
src/Infrastructure/Persistence/Migrations/20240415072043_Remove_Hero_Team_EF_Config_RequiredFlag.cs
src/WebApi/Features/HeroEndpoints.cs
src/WebApi/Program.cs
tests/Domain.UnitTests/Heroes/HeroTests.cs
tests/Domain.UnitTests/Teams/TeamTests.cs
tests/WebApi.IntegrationTests/Common/Factories/HeroFactory.cs
tests/WebApi.IntegrationTests/Endpoints/Heroes/Commands/CreateHero/CreateHeroCommandTests.cs
tests/WebApi.IntegrationTests/Endpoints/Heroes/Commands/UpdateHero/UpdateHeroCommandTests.cs
tests/WebApi.IntegrationTests/Endpoints/Heroes/Queries/GetAllheroes/GetAllHeroesQueryTests.cs

This PR implements part of #287 .
What is still in TODO:
- Delete endpoint for Hero
- Team CRUD endpoint
- Removal of Todo models
- Added Heroes CRU endpoint 
- Fix Hero - Team accidental required FK constraint in DB
✏️ No

✨  Add CRU endpoints for Hero

---

src/Domain/Teams/Mission.cs
src/Infrastructure/Persistence/ApplicationDbContextInitializer.cs
src/WebApi/appsettings.Development.json

✏️ #295 
✏️ Heros, Teams, and Missions are now populated via seed data
✏️ No

✨ Heroes domain now has seed data

---

src/Application/Features/Teams/Queries/GetAllTeams/GetAllHeroesQuery.cs
src/Application/Features/Teams/Queries/GetAllTeams/GetAllTeamsMapping.cs
src/Application/Features/Teams/Queries/GetAllTeams/TeamDto.cs
src/WebApi/Features/TeamEndpoints.cs
tests/WebApi.IntegrationTests/Common/Factories/HeroFactory.cs
tests/WebApi.IntegrationTests/Common/Factories/TeamFactory.cs
tests/WebApi.IntegrationTests/Endpoints/Teams/Queries/GetAllHeroesQueryTests.cs

✏️ #317 
✏️ Added endpoint, query, and tests to get all teams
✏️ No

✨ Added Get Teams Query

---

src/Application/Features/Teams/Commands/ExecuteMission/SendTeamOnMissionCommand.cs
src/WebApi/Features/TeamEndpoints.cs
src/WebApi/WebApi.http
tests/WebApi.IntegrationTests/Common/Fixtures/IntegrationTestBase.cs
tests/WebApi.IntegrationTests/Endpoints/Teams/Commands/ExecuteMissionCommandTests.cs

✏️ #319 
✏️ Added endpoint, command, and test for executing a misison
✏️ No

✨ 319 DDD Execute a Mission

---

src/Application/Features/Teams/Events/TodoItemCreatedEventHandler.cs
src/Domain/Heroes/Hero.cs
src/Domain/Heroes/PowerLevelUpdatedEvent.cs
src/Domain/Teams/Team.cs
src/Infrastructure/Persistence/Configuration/HeroConfiguration.cs
src/Infrastructure/Persistence/Configuration/TeamConfiguration.cs
src/Infrastructure/Persistence/Interceptors/DispatchDomainEventsInterceptor.cs
src/WebApi/Features/HeroEndpoints.cs
tests/Domain.UnitTests/Heroes/HeroTests.cs
tests/WebApi.IntegrationTests/Common/Fixtures/ServiceCollectionExt.cs
tests/WebApi.IntegrationTests/Endpoints/Teams/Commands/AddHeroToTeamCommandTests.cs
tests/WebApi.IntegrationTests/Endpoints/Teams/Events/UpdatePowerLevelEventTests.cs

✏️ #264
✏️ Added an event handler to update Team Power, when an individual heroes power is updated
✏️ No

✨ DDD Add Better Domain Event Example

---

CleanArchitecture.nuspec

✏️ #332
✏️ Updated nuget version
✏️ No

332--publish-new-version

---

CleanArchitecture.nuspec

Nuget package - change link from archived repo to new repo

---

docs/adr/20240605-use-minimal-api-typed-results.md
docs/adr/20240605-use-results-pattern-over-exceptions.md

✏️  I noticed that there were comments making the ADRs look messy
✏️ removed comments
✏️ No

cleanup comments

---

Directory.Build.props
src/Application/Application.csproj
src/Domain/Domain.csproj
src/Infrastructure/Infrastructure.csproj
src/WebApi/WebApi.csproj
tests/Architecture.Tests/Architecture.Tests.csproj
tests/Domain.UnitTests/Domain.UnitTests.csproj
tests/WebApi.IntegrationTests/WebApi.IntegrationTests.csproj
tools/Database/Database.csproj

✏️ https://github.com/SSWConsulting/SSW.CleanArchitecture/issues/375
✏️ Consolidated management of .NET Framework to Build.Directory.props
✏️ No

✨ Migrate .NET version to Build.Directory.props

---

src/WebApi/IWebApiMarker.cs
src/WebApi/Program.cs
tests/WebApi.IntegrationTests/Common/Fixtures/IntegrationTestWebApplicationFactory.cs

✏️  https://github.com/SSWConsulting/SSW.CleanArchitecture/issues/381
✏️ Added marker interface
✏️  No

♻️ Use marker interface instead of partial program

---

src/Domain/Domain.csproj
src/Domain/GlobalUsings.cs
src/Domain/Heroes/Hero.cs
src/Domain/Heroes/Power.cs
src/Domain/Heroes/PowerLevelUpdatedEvent.cs
src/Domain/Teams/Mission.cs
src/Domain/Teams/Team.cs
tests/Domain.UnitTests/Heroes/HeroTests.cs
tests/Domain.UnitTests/Heroes/PowerTests.cs

✏️ https://github.com/SSWConsulting/SSW.CleanArchitecture/issues/380
✏️ Removed Ardalis.Guard clauses in favour of OOTB .NET Guard Clauses
✏️  No

♻️ Removed Ardalis.Guard library in favor of built in .NET Guard clauses.

---

docs/adr/20241023-use-net-openapi-and-scalar-over-nswag-and-swagger.md

📝 ADR - OpenAPI + Scalar vs Nswag + SwaggerUI

---

tools/AppHost/AppHost.csproj

✏️  https://github.com/SSWConsulting/SSW.CleanArchitecture/issues/391
✏️ Aspire containers now remain running after stopping the local application
✏️ No

🐛 Fixed persistent Aspire containers

---

Directory.Build.props
src/WebApi/DependencyInjection.cs

Build failed
Another file decided to fight us on linux. Ignored warning.
No.

🐛 Fix Build

---

src/Application/Application.csproj
src/Domain/Domain.csproj
src/WebApi/WebApi.csproj
tests/Directory.Packages.props

⬆️ Bump NuGet Packages

---

CleanArchitecture.nuspec
README.md

✏️ https://github.com/SSWConsulting/SSW.CleanArchitecture/issues/394
✏️ Updated readme and bumped version number
✏️ Yes - @MattParkerDev

394  ca template   release nuget package

---

CleanArchitecture.nuspec

✏️ https://github.com/SSWConsulting/SSW.CleanArchitecture/issues/417
✏️ Update nuget package
✏️ No

Bump version to 2024.11.04

---

tools/MigrationService/Initializers/DbContextInitializerBase.cs

✏️ https://github.com/SSWConsulting/SSW.CleanArchitecture/issues/419
✏️ Fixed a bug when running Aspire twice without migrations
✏️ No

🐛 Aspire - Check if tables exist before creating

---

tools/AppHost/Commands/SqlServerCommandExt.cs
tools/AppHost/Program.cs
tools/MigrationService/Worker.cs

✏️ https://github.com/SSWConsulting/SSW.CleanArchitecture/issues/421
✏️ Moved drop DB command to database resource
✏️ No

🐛 Aspire - Fixed drop database command

---

CleanArchitecture.nuspec

✏️ https://github.com/SSWConsulting/SSW.CleanArchitecture/issues/423
✏️ Deploy nuget package
✏️ No

🚀 Deploy Nuget Package 2024.11.06 (#418)

---

CleanArchitecture.nuspec

https://github.com/SSWConsulting/SSW.CleanArchitecture/issues/445
This pull request includes a small change to the `CleanArchitecture.nuspec` file. The change updates the version number from `2024.11.06` to `2024.11.19`.
No

🚀 Deploy Nuget Package 2024.11.19

---

README.md

Add dependencies to readme

---

src/Domain/Domain.csproj

> 1. What triggered this change? (PBI link, Email Subject, conversation + reason, etc)
✏️ Luke C raised issue with Vogen running on latest .NET 9
✏️ Updated Vogen to latest
✏️ No

Upgraded Vogen to latest version

---

src/Application/UseCases/Heroes/Commands/UpdateHero/UpdateHeroCommand.cs
src/Domain/Heroes/Hero.cs
src/Domain/Teams/Team.cs

PR comment from @AntPolkanov on client work
This pull request includes several changes to the `Hero` and `Team` classes in the domain layer to improve encapsulation and validation. The most important changes include refactoring property setters to include validation and removing unnecessary update methods.
Improvements to encapsulation and validation:
* [`src/Domain/Heroes/Hero.cs`](diffhunk://#diff-094ca6729cc59148d9d65db00c747f8731a9f56aed4f12867002e9a94daa978eL12-R35): Refactored `Name` and `Alias` properties to include validation in their setters and removed the `UpdateName` and `UpdateAlias` methods. [[1]](diffhunk://#diff-094ca6729cc59148d9d65db00c747f8731a9f56aed4f12867002e …

♻️ Replaced simple aggregate functions with direct use of properties.

---

CleanArchitecture.nuspec

✏️ update version to 2025.03.03
✏️ version bump
✏️ No

🚀 Bump version to 2025.03.03 in CleanArchitecture.nuspec

---

.github/workflows/package.yml

♻️ Add workflow_dispatch inputs for manual package creation and update NuGet version to latest

---

.github/workflows/package.yml
CleanArchitecture.nuspec

✏️ nuget package action not running
✏️ Fixed tabs
✏️ No

♻️ Fix indentation for workflow_dispatch in package.yml

---

src/Application/UseCases/Teams/Commands/CompleteMission/CompleteMissionCommand.cs
src/Domain/Heroes/Hero.cs
src/Domain/Teams/Team.cs
src/Domain/Teams/TeamErrors.cs
src/WebApi/Endpoints/TeamEndpoints.cs
tests/Domain.UnitTests/Teams/TeamTests.cs

✏️ #488
✏️ Fixed up team endpoint that was not correctly returning errors
✏️ Yeah with Luke C

♻️ Refactor mission completion logic and add error handling for empty teams

---

Directory.Packages.props

This pull request includes a version update for the `Ardalis.Specification` and `Ardalis.Specification.EntityFrameworkCore` packages in the `Directory.Packages.props` file.
Version updates:
* Updated `Ardalis.Specification` from version `8.0.0` to `9.0.1`.
* Updated `Ardalis.Specification.EntityFrameworkCore` from version `8.0.0` to `9.0.1`.

⬆️ Update Ardalis.Specifications

---

src/Domain/Common/Base/Auditable.cs
src/Domain/Common/Interfaces/IAuditable.cs
src/Domain/Heroes/Hero.cs
src/Domain/Heroes/Power.cs
src/Domain/Teams/Mission.cs
src/Domain/Teams/Team.cs
src/Infrastructure/Persistence/ApplicationDbContext.cs
src/Infrastructure/Persistence/Configuration/AuditableConfiguration.cs
src/Infrastructure/Persistence/Configuration/HeroConfiguration.cs
src/Infrastructure/Persistence/Configuration/MissionConfiguration.cs
src/Infrastructure/Persistence/Configuration/TeamConfiguration.cs
src/Infrastructure/Persistence/Interceptors/EntitySaveChangesInterceptor.cs
src/Infrastructure/Persistence/Migrations/20250319113414_Initial.Designer.cs
src/Infrastructure/Persistence/Migrations/20250319113414_Initial.cs
src/Infrastructure/Persistence/Migrations/ApplicationDbContextModelSnapshot.cs
tools/MigrationService/MigrationUserService.cs
tools/MigrationService/Program.cs

This pull request includes several changes aimed at improving the domain models and their configurations, as well as ensuring consistency and proper validation across the codebase. The most important changes include adding maximum length constraints, updating method signatures, and modifying entity configurations.
* [`src/Domain/Common/Base/Auditable.cs`](diffhunk://#diff-7f61c1a655bdfa4cd99a37fba4dcc331ab6a49393378babd32b03927376e375cR8-R50): Added constants for `CreatedByMaxLength` and `UpdatedByMaxLength`, and updated setters to include validation for maximum length and non-null values. Updated `SetCreated` and `SetUpdated` methods to use `TimeProvider`.
* [`src/Domain/Heroes/Hero.cs`](diffhunk://#diff-094ca6729cc59148d9d65db00c747f8731a9f56aed4f12867002e9a94daa978eR11-R13): Added …

✨ validate string lengths in domain

---

README.md

This pull request updates the folder structure in the `README.md` file to align with a new organizational pattern. The changes replace references to the `Features` directory with the `UseCases` directory.
Folder structure updates in `README.md`:
* Updated the path for creating a query to use `src/Application/UseCases` instead of `src/Application/Features`.
* Updated the path for creating a command to use `src/Application/UseCases` instead of `src/Application/Features`.

📝 Fixed folder name in readme instructions

---

Directory.Packages.props
tools/AppHost/AppHost.cs
tools/AppHost/AppHost.csproj

⚠️ Merged without review by @danielmackay 
This pull request includes updates to package versions, refactors to improve code clarity, and adjustments to project dependencies. The most important changes are grouped by theme below.
* [`Directory.Packages.props`](diffhunk://#diff-5baf5f9e448ad54ab25a091adee0da05d4d228481c9200518fcb1b53a65d4156L12-R14): Updated versions of `Aspire.Hosting.AppHost`, `Aspire.Hosting.SqlServer`, and `Aspire.Microsoft.EntityFrameworkCore.SqlServer` from `9.3.x` to `9.4.0`.
* [`tools/AppHost/AppHost.cs`](diffhunk://#diff-db0e56ef74293b7fca78df3556828fab61241b9c4c817fa0097653b574157d3bL6-R8): Refactored the SQL Server configuration by removing the hardcoded port value to improve flexibility. The port parameter is now commented out and optional.
* …

⬆️ Update Aspire to 9.4

---

CleanArchitecture.nuspec

⚠️ Merged without review by @danielmackay 
This pull request makes updates to the `CleanArchitecture.nuspec` file, including a version change and formatting adjustments for clarity and readability.
* **Version Update**: Changed the package version from `2025.07.02` to `2025.08.03` to reflect the latest release.
* **Formatting Adjustment**: Reformatted the `exclude` attribute in the `<file>` element to improve readability and maintain consistent indentation.

🚀 Bump version to 2025-08-03

---

Directory.Packages.props
README.md
src/Infrastructure/DependencyInjection.cs
tests/WebApi.IntegrationTests/Common/Infrastructure/Web/WebApiTestFactory.cs
tools/AppHost/AppHost.cs
tools/AppHost/AppHost.csproj
tools/AppHost/Commands/SqlServerCommandExt.cs
tools/MigrationService/Program.cs

This pull request introduces Azure deployment support and modernizes the project configuration to leverage Aspire Azure hosting packages, while also improving documentation and consistency. The main changes are grouped below.
**Azure deployment and hosting integration:**
* Added Aspire Azure hosting packages (`Aspire.Hosting.Azure.ApplicationInsights`, `Aspire.Hosting.Azure.AppService`, `Aspire.Hosting.Azure.Sql`) to `Directory.Packages.props` and `AppHost.csproj`, replacing the previous SQL Server hosting package. [[1]](diffhunk://#diff-5baf5f9e448ad54ab25a091adee0da05d4d228481c9200518fcb1b53a65d4156R8-R10) [[2]](diffhunk://#diff-cda82b6742843f6c1767221e433612d9fa582a55058b1f5ee6a5563151ba4656L13-R16)
* Refactored `AppHost.cs` to use Azure App Service and Azure SQL resources for API and …

✨ deploy to azure from aspire

---

CleanArchitecture.nuspec

This pull request makes a minor update to the `CleanArchitecture.nuspec` file, incrementing the package version number. No other changes are included.
* Bumped the package version from `2025.08.03` to `2025.08.12` in `CleanArchitecture.nuspec`.

🚀 Bump version to 2025.08.12 in nuspec file
